### ISSUE TITLE
Install the dependency of Pillow module

### ISSUE THREAD

**Issue by alokemajumder** [bongdevhq/profile-showcase#26]
The pillow module of python is not getting installed via Actions . And the build is failing .

**Comment by Sayanabha** [comment]
@bongdevhq 
Please allow me solve the issue.

**Comment by bongdev** [comment]
Hi, @Sayanabha , Thanks for your interest . We really appreciate it . Please feel free to go ahead . This has been assigned to you.

**Comment by Sohamsdays** [comment]
@bongdev  I think its already been fixed by @chiraagbanerjee. Check my run, under the installations, it shows successfully installed Pillow.  https://github.com/bongdevhq/profile-showcase/actions/runs/6481128361/job/17598038966

**Comment by bongdev** [comment]
@chiraagbanerjee can you please check the 'PIL' part if that is working? As @Sohamsdays mentioned, it seems Pillow is now fixed though.

**Comment by chiraagbanerjee** [comment]
I think pillow has been installed correctly also it's working within the python script perfectly,i think the problem is that the changes the script is making not getting reflected in repo.

**Comment by bongdev** [comment]
This is fixed
