### ISSUE TITLE
Read More button don't have clear symbol

### ISSUE THREAD

**Issue by ItsRoy69** [bongdevhq/profile-showcase#35]
**Describe the bug**
The "Read More" button icon is not getting rendered. 

**To Reproduce**
1. Go to 'https://bong.dev/'
2. Scroll down to 'Latest Article'
3. Check that the buttons of the blogs are not showing proper icons

**Expected behavior**
Arrow or something like that would've shown

**Screenshots**
![image](https://github.com/bongdevhq/profile-showcase/assets/78967360/7c97cb98-df3e-405e-aab5-65825e3a73d2)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Edge]

**Comment by bongdev** [comment]
Hi Roy , Thanks a lot for pointing this . The site is on wordpress and out of the scope here . I will definitely pass your information to the website team. 

Thanks again .
