### ISSUE TITLE
[Refactor]: Change Twitter icon to X

### ISSUE THREAD

**Issue by Ghat0tkach** [bongdevhq/profile-showcase#6]
Since Twitter is changed to X , we need to change its logo as well.

I would love to work on this issue as part of hacktoberfest

**Comment by hoichoidev** [comment]
Can you please elaborate and share the steps to reproduce ? 

Thanks

**Comment by bongdev** [comment]
Can you please elaborate and share the steps to reproduce ? 

Thanks

**Comment by Ghat0tkach** [comment]
@bongdev ,

Im talking about the current twitter logo which need to be changed to X 

![image](https://github.com/bongdevhq/profile-showcase/assets/59855919/74798e1b-5f2e-4485-9e18-2332dc2d042b)

**Comment by 4artiseth** [comment]
@Ghat0tkach @bongdev 
Is the code of the website open source on here? I cant seem to find it to make changes.
Please revert back for the issues to be addressed.

**Comment by bongdev** [comment]
Hi, The website's code is not available here. The site is made with wordpress. So closing this .
